name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify your Java version

      - name: Compile Java Code
        run: |
          mkdir -p bin
          javac -d bin src/*.java

      - name: Run Tests
        run: |
          java -cp bin org.junit.runner.JUnitCore TestClassName  # Replace with your actual test class name

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: java-build
          path: bin
